---

- hosts: localhost

  tasks:
   - name: get ansible date/time facts
     setup:
       filter: "ansible_data_time"
       gather_subset: "!all"

   - name: store dtg as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"
   
   - name: create direc 
     file:
      path: /etc/ansible/store/{{ hostvars.localhost.DTG }}
      state: directory
  run_once: true      

