---

- name: backup config
  hosts: Router
  gather_facts: true
  connection: network_cli

  tasks:
   - name: sh run 
     ios_command:
       commands:
       - show run
     register: config

   - name: save output to /etc/ansible/backups
     copy:
      content: "{{ config.stdout | replace('\\n', '\n') }}"
      dest: "/etc/ansible/backups/show_run_{{ inventory_hostname }}.txt"   
