---

- name: reload the device
  hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
  - name: reload
    cli_command: 
      command: reload
      prompt:
        - confirm      
      answer:
        - 'y'     
