---

- name: save running config
  hosts: R1
  gather_facts: false
  connection: network_cli
  
  tasks:
    - name: write config         
      ios_command:
        commands: write      
      register: output
      
    - name: print output
      debug:
        var: output.stdout_lines

